-- Update medicines table with new data
TRUNCATE TABLE medicines;

-- Insert updated medicine data
INSERT INTO medicines (name, description, price, category, manufacturer, in_stock, image_url, dosage, form, origin) VALUES
('Ambroxol', 'Expectorant used to treat respiratory diseases with excessive mucus', 120.50, 'respiratory', 'TGP Pharma Inc.', true, 'https://vvxeewfhaleyarchczbx.supabase.co/storage/v1/object/public/medicine/ambroxol.jpg', '30mg', 'Tablet', 'Philippines'),
('Amlodipine', 'Calcium channel blocker used to treat high blood pressure and coronary artery disease', 350.75, 'cardiovascular', 'Sandoz Pharmaceuticals', true, 'https://vvxeewfhaleyarchczbx.supabase.co/storage/v1/object/public/medicine/amlodipine.jpg', '5mg', 'Tablet', 'Philippines'),
('Asmagone (Salbutamol Sulfate)', 'Bronchodilator that relaxes muscles in the airways, used to treat asthma', 420.00, 'respiratory', 'TGP Pharma Inc.', true, 'https://vvxeewfhaleyarchczbx.supabase.co/storage/v1/object/public/medicine/asmagone-salburamol-sulfate.jpg', '25mg/25ml', 'Nebules', 'Philippines'),
('Benedex (Amoxicillin)', 'Antibiotic used to treat bacterial infections', 650.00, 'antibiotics', 'TGP Pharma Inc.', true, 'https://vvxeewfhaleyarchczbx.supabase.co/storage/v1/object/public/medicine/benedex-amoxicillin.jpg', '500mg', 'Capsule', 'Philippines'),
('Butamirate Citrate', 'Antitussive medication used to relieve cough', 180.25, 'respiratory', 'Actimed Pharmaceuticals', true, 'https://vvxeewfhaleyarchczbx.supabase.co/storage/v1/object/public/medicine/butamirate-citrate.jpg', '50mg', 'Syrup', 'Philippines'),
('Butamirate Citrate Tablet', 'Antitussive medication used to relieve cough', 195.50, 'respiratory', 'Actimed Pharmaceuticals', true, 'https://vvxeewfhaleyarchczbx.supabase.co/storage/v1/object/public/medicine/butamirate-citrate-tablet.jpg', '50mg', 'Tablet (10s)', 'Philippines'),
('Cepham (Cefalexin)', 'Antibiotic used to treat bacterial infections', 520.75, 'antibiotics', 'TGP Pharma Inc.', true, 'https://vvxeewfhaleyarchczbx.supabase.co/storage/v1/object/public/medicine/cepham-cefalexin-cap.jpg', '250mg', 'Capsule', 'Philippines'),
('Dextro (Dextromethorphan)', 'Cough suppressant used to treat cough caused by the common cold or flu', 220.50, 'respiratory', 'TGP Pharma Inc.', true, 'https://vvxeewfhaleyarchczbx.supabase.co/storage/v1/object/public/medicine/dextro-dextromethorphan-tablet.jpg', '10mg', 'Tablet (10s)', 'Philippines'),
('Guaiflem (Guaifenesin)', 'Expectorant used to reduce chest congestion caused by colds or infections', 180.75, 'respiratory', 'TGP Pharma Inc.', true, 'https://vvxeewfhaleyarchczbx.supabase.co/storage/v1/object/public/medicine/guaiflem-guaifenesin.jpg', '100mg/5ml', 'Syrup (120ml)', 'Philippines'),
('LemonCee (Ascorbic Acid)', 'Vitamin C supplement used to prevent and treat scurvy', 85.75, 'vitamins', 'TGP Pharma Inc.', true, 'https://vvxeewfhaleyarchczbx.supabase.co/storage/v1/object/public/medicine/lemoncee-ascorbic-acid-drops.jpg', '100mg/15ml', 'Drops', 'Philippines'),
('Losartan', 'Angiotensin II receptor blocker used to treat high blood pressure', 380.50, 'cardiovascular', 'RiteMED Phils. Inc.', true, 'https://vvxeewfhaleyarchczbx.supabase.co/storage/v1/object/public/medicine/losartan.jpg', '50mg', 'Tablet', 'Philippines'),
('Megalin (Mefenamic Acid)', 'Non-steroidal anti-inflammatory drug used for pain relief', 150.00, 'painkillers', 'TGP Pharma Inc.', true, 'https://vvxeewfhaleyarchczbx.supabase.co/storage/v1/object/public/medicine/megalin-mefenamic-acid.jpg', '250mg', 'Capsule (10s)', 'Philippines'),
('Paracetamol', 'Analgesic and antipyretic used for pain relief and fever reduction', 120.50, 'painkillers', 'TGP Pharma Inc.', true, 'https://vvxeewfhaleyarchczbx.supabase.co/storage/v1/object/public/medicine/paracetamol.jpg', '500mg', 'Tablet (10s)', 'Philippines'),
('Acetylcysteine', 'Mucolytic agent used to treat conditions with thick mucus', 320.00, 'respiratory', 'TGP Pharma Inc.', true, 'https://vvxeewfhaleyarchczbx.supabase.co/storage/v1/object/public/medicine/acetylcysteine.jpg', '600mg', 'Powder Sachet', 'Philippines'),
('Carbocisteine', 'Mucolytic agent used to reduce phlegm and thin mucus', 280.25, 'respiratory', 'Actimed Pharmaceuticals', true, 'https://vvxeewfhaleyarchczbx.supabase.co/storage/v1/object/public/medicine/carbocisteine.jpg', '500mg', 'Capsule', 'Philippines'),
('Diamet (Metformin HCl)', 'Oral diabetes medicine that helps control blood sugar levels', 250.00, 'endocrine', 'TGP Pharma Inc.', true, 'https://vvxeewfhaleyarchczbx.supabase.co/storage/v1/object/public/medicine/diamet-metformin-hci.jpg', '500mg', 'Tablet', 'Philippines'),
('Losartan Potassium + Amlodipine', 'Combination medication for treating high blood pressure', 450.75, 'cardiovascular', 'RiteMED Phils. Inc.', true, 'https://vvxeewfhaleyarchczbx.supabase.co/storage/v1/object/public/medicine/losartan-potassium-amlodipine.jpg', '50mg/5mg', 'Tablet', 'Philippines'),
('Myrex (Carbocisteine)', 'Mucolytic agent used to reduce phlegm and thin mucus in children', 210.50, 'respiratory', 'Actimed Pharmaceuticals', true, 'https://vvxeewfhaleyarchczbx.supabase.co/storage/v1/object/public/medicine/myrex-carbocisteine-drops.jpg', '50mg/ml', 'Drops (15ml)', 'Philippines'),
('Nepidol (Amlodipine)', 'Higher dose calcium channel blocker for severe hypertension', 395.25, 'cardiovascular', 'Sandoz Pharmaceuticals', true, 'https://vvxeewfhaleyarchczbx.supabase.co/storage/v1/object/public/medicine/nepidol-amlodipine-tab.jpg', '10mg', 'Tablet', 'Philippines'),
('Tramacort (Clotrimazole)', 'Antifungal medication used to treat skin infections', 175.00, 'dermatological', 'TGP Pharma Inc.', true, 'https://vvxeewfhaleyarchczbx.supabase.co/storage/v1/object/public/medicine/tramacort-clotrimazole.jpg', '20g', 'Cream', 'Philippines');